analytics.account={"id"\:1684511,"name"\:"My Account_01","uuid"\:"746f7af3-caf3-4002-ab43-d8ba5eac3daf","domain"\:"ac-1684511"}
analytics.integration.enable=true
analytics.onpremise.enable=true
analytics.onpremise.organization=null
analytics.onpremise.server=https\://testops.katalon.io
analytics.project={"id"\:3479807,"name"\:"OrangeHRM Trial \#3479807","teamId"\:3467616,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3499277,"sampleProject"\:false,"autoIntegrate"\:false,"accountId"\:null}
analytics.team={"id"\:3467616,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=false
analytics.testreport.autoupload.enable=true
onpremise.email=muhammad.afdhal.f01@gmail.com
onpremise.password=sTbJI9q46YFctsbTyIA32FdCCufDzvHy
