<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnOpenLoginModal</name>
   <tag></tag>
   <elementGuidId>cc2359ef-1824-417e-a9eb-4d50b66f9ac4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-label=&quot;Open\ Sign\ In\ Modal&quot;] .iconify--mdi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-label = 'Open Sign In Modal']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' iconify--mdi ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Open Sign In Modal&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>eaab5b34-1bb2-4e72-b738-e71b3d001f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>94d61287-e27e-4fd7-9053-2d424aa18615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns:xlink</name>
      <type>Main</type>
      <value>http://www.w3.org/1999/xlink</value>
      <webElementGuid>01eb13cf-9f88-4a63-b0a1-f942ccbce0da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b18a86e3-b2b0-40ec-b708-19d745c1ce65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d7b16eba-8cd8-4d46-92fc-1c2b82423757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iconify iconify--mdi text-2xl</value>
      <webElementGuid>721aea1b-616e-469c-939c-93b7109ac67e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>c2a4e38d-0dbd-409f-928b-0c46609ed7c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>b857275a-e09d-45af-b3f6-1c52893d107c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>955c1db3-ac6f-4ebb-bc0e-3b1ac008b3ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-9bfeb911be8d7fcf3f5e6461aab42c62</value>
      <webElementGuid>e97c72bb-8eac-47e0-8b2e-ba43659fb749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-label = 'Open Sign In Modal']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' iconify--mdi ')]</value>
      <webElementGuid>aed80431-aed0-4451-a1b3-78fcaf31b7cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-label = 'Open Sign In Modal']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' iconify--mdi ')]</value>
      <webElementGuid>ab8a4c06-a99d-4ccc-a768-db95102c21fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
