<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txfEmail</name>
   <tag></tag>
   <elementGuidId>5057d29c-85b8-4495-aec6-cd75b1ae10ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='Enter your Email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[type=&quot;text&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter your Email&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df05e8f6-80fa-4ef0-b374-f44019477529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your Email</value>
      <webElementGuid>a2ecd14a-44f4-40cb-9d5a-b780d12b605d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-1 rounded-full bg-white text-black px-6 py-4 text-sm outline-none placeholder:text-gray-500</value>
      <webElementGuid>c50a9ffe-5f7e-40a8-8451-5f672bee9fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1caf6362-9564-4fcb-ae2a-ed27e704770d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a86b7aad82b159b198e69438a103d96a</value>
      <webElementGuid>143a0e2c-8b55-46a6-a1d4-8c25d1a1c639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@type = 'text']</value>
      <webElementGuid>9f48826f-c34d-4b6f-ac29-1ccdcd663011</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@type = 'text']</value>
      <webElementGuid>839f9990-7bbc-49ad-81bc-df9748dcb2ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter your Email' and @type = 'text']</value>
      <webElementGuid>6c5f3c5b-ec56-4615-b26c-f150ad5979f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
