<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>drpFilterCategory</name>
   <tag></tag>
   <elementGuidId>baae3098-85dc-424b-9a99-2b0814dca712</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//select)[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
