<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txfOrder</name>
   <tag></tag>
   <elementGuidId>dda72c87-32b2-4e1c-b648-5602391c5a55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='number']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=spinbutton</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffe0014a-961f-44f8-878a-851be819b9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full rounded-xl bg-black/30 border border-white/10 px-4 py-3 outline-none focus:border-white/20</value>
      <webElementGuid>c3dba1e6-adbd-47ff-8a4e-342c59ba9ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>652e461b-0864-4cc6-bf1d-87669940266b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>f1bf0f4d-fb86-4037-be8b-f883681d1226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;dark&quot;]/body[@class=&quot;__className_0d7163&quot;]/div[@class=&quot;min-h-screen text-white flex&quot;]/div[@class=&quot;flex-1 flex flex-col&quot;]/main[@class=&quot;p-4 md:p-6&quot;]/div[@class=&quot;space-y-6&quot;]/div[@class=&quot;fixed inset-0 z-[9999] flex items-center justify-center bg-black/70 p-4&quot;]/div[@class=&quot;w-full max-w-3xl rounded-2xl border border-white/10 bg-[#0D0D0D] overflow-hidden&quot;]/div[@class=&quot;p-6 space-y-5&quot;]/div[@class=&quot;grid grid-cols-1 md:grid-cols-2 gap-4&quot;]/div[2]/input[@class=&quot;w-full rounded-xl bg-black/30 border border-white/10 px-4 py-3 outline-none focus:border-white/20&quot;]</value>
      <webElementGuid>51508e9a-f3f4-46ad-a0df-34becfa8361f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='6']</value>
      <webElementGuid>ba4f1b89-eb6a-474f-acf7-e8a138583f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>08802014-67db-439a-a013-74aa5aa4beaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number']</value>
      <webElementGuid>6910ad2e-81fc-408b-a08a-b055823d88a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
